const dna = 'TGTCGCTGAGAGACGGCCGCGTTAATCGGTGCTTCACAGCTTCCGACATGACATGACCATAAGTATAAAGTCGCCCTGGGGTCAAACGATATCCGCAAGCTCGCCCCAGACTTGGAGTGGCAGCCAGATGAGGATGTCCTTCGTAACATACCTAGAGCCGAGATACAGAGGGCTACCTAAATCTCGCTCCTGGCGGTAGACTCGAAGCCAGGAGGTGACTGGGGGTCCTCTCCCCGGCACCATGCACTGACTGTCAGAAGGCACGTACGACAATTTGGTTGGCTAAATGTTATACGTCCCATGAGACCCACCATGGGTAGCATCCGACTGTGCCGTTATCCAGGTCAGACATGGAGTTTGCACGCGCTGGGCACTTCCATAGATCTAGCTATGATGATCGTACTAAGTGGTATGCAGACCGACCGGTCAGGGAGTACTCCTAACAATGGGCCGCTCCCTAACCAGCCTGGTGGCCGTCGTTCACCTGGGTTGTATGCTGTCGTGACCTGAACGGCGCACACTCTAGTTTACGGCAGAAACTCTTGTCCGCCACGCGGGGTCAGGAGACTCAACTTATCTCGTGTTGACCATGCTAAGTTAGAAGTATGAAAGTGTCTAAGATTCAATTGATGTGAGACGCGAACGGACGTGGCGAAGTTCAGGTTTCACACACCCGGTATAGGGTCGCGACTTCATGAGGCGTGCGATTAGCCTTCGTCGCTAAACAACGGCTACGGAAGGTGTGCGAGACGGCCTACACTTAGTTTCTTGTTAAGTAATTGGGTCACTGTGCACATTATTGAAGTAG'
let reverseComplement = ''

const complements = new Map([
  ['A', 'T'],
  ['T', 'A'],
  ['C', 'G'],
  ['G', 'C'],
])

for (let i = dna.length-1; i >= 0; i--) {
  reverseComplement += complements.get(dna[i])   
}

console.log(reverseComplement)
